name: Setup Node
description: Checkout repo and install dependencies
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: npm
    - name: Install dependencies
      shell: bash
      run: npm ci
